### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by craftzdog** [ebigram/emojisense#2]
Hey, thank you for creating a plugin. It's Takuya.

I checked out your plugin and found an issue in `package.json`.
You don't have to add `electron`, `event-kit`, `react`, or `react-dom` as the dependencies because the app provides them.
Having a dependency on `electron` causes downloading a large Electron binary file when installing the plugin.

**Comment by craftzdog** [comment]
You can remove `react` and `react-dom`

**Comment by ebigram** [comment]
Oof, I cleaned that up now, I had to take a brief hiatus and didn't have a chance to to undo some shotgun debugging. Closing for now, but there will be more purging later!
