### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by arkag** [ebigram/emojisense#3]
I get this error popping up on install. I *think* this occurred in v4 as well, but I'm now getting the error on v5.

![image](https://user-images.githubusercontent.com/6749810/92003285-15cfa700-ecfe-11ea-8846-d5e512f8ebd1.png)

**Comment by ebigram** [comment]
Yeah, that's a very sad emoji 👎 . Thank you for reporting that, I'll look into it immediately.

**Comment by ebigram** [comment]
Not ideal, but reverting to #f3c3a2f v0.2.2 should fix it for now. Seemed to happen when I was working against the beta, but that might not be relevant actually. @arkag please LMK if this regression resolves it, I've had a backlog I've been meaning to go through anyway.

**Comment by arkag** [comment]
Looks like that's the latest commit on my end: f3c3a2f8ce66f830c0339021f7b2e97b6302d5a4, right? I just cloned and set this up via `ipm link --dev`.

**Comment by arkag** [comment]
In fact... Looks like the latest change to "real" code, which is to say non-document files, is at `706e28091ca5720caf187f6d61478aeab72d0d14`. Weird...

**Comment by ebigram** [comment]
Yeah that's cause I temporarily did some rebasing surgery while I figure this out. I'll play everything back in a bit, just wondering if that removed the offending issue for you or not, because I'm having trouble reproducing it. Either way, I figured out the issue, so I'll restore Inkdrop version <-> commit history parity soon.

**Comment by arkag** [comment]
It changed the error, if that helps haha 

<img width="349" alt="image" src="https://user-images.githubusercontent.com/6749810/92243121-77377780-eeb0-11ea-8877-21555047ae89.png">

**Comment by arkag** [comment]
Ah, I suppose when running dev builds module management is important huh xD... I did `npm i` got some errors but it seems to be working now.

**Comment by ebigram** [comment]
Well thanks for taking the time; I'm a bit green to front-end dev, but this will get its due diligence.

**Comment by arkag** [comment]
No worries! I would love to help get this working. Let me know if you need anything, though full disclosure I am very green on the Javascript side, haha.

**Comment by ebigram** [comment]
Think it should be set, please open another issue if still running into problems since it should at least be a _different_ one.
