### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by m4l0n** [ebigram/emojisense#8]
Is this still being maintained? I tried it to no avail. There's no autocompletion of emojis and I had to type out the full name.

**Comment by ebigram** [comment]
Sorry, I was on hiatus due to illness, can you try it now?

**Comment by ksmxxxxxx** [comment]
Hi, how are you feeling? I wish you well.
I tried autocomplete. It worked fine.
Thank you for the great plugin 🎁

**Comment by ebigram** [comment]
Thanks for the well wishes, slowly getting better hopefully! Enjoy.
